CREATE TABLE [dbo].[FeedPostLikes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EventLogId] [int] NOT NULL,
	[UserProfileId] [int] NOT NULL,
 CONSTRAINT [PK_FeedPostLikes] PRIMARY KEY CLUSTERED 
(
	[EventLogId] ASC,
	[UserProfileId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]